version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ee:16.11.1-ee.0
    restart: always
    hostname: gitlab.solvera.com.tr
    container_name: gitlab-ee
    environment:
      GITLAB_ROOT_PASSWORD: "changeMeToSomethingGood"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.solvera.com.tr'
        letsencrypt['contact_emails'] = ['erkan.kamazoglu@solvera.com.tr']
        registry_external_url 'https://gitlab.solvera.com.tr:5010'
        registry['enable'] = true
        nginx['redirect_http_to_https'] = true 
        nginx['ssl_protocols'] = "TLSv1.2 TLSv1.3" 
        registry_nginx['enable'] = true 
        registry_nginx['listen_port'] = 5010  
        gitlab_rails['time_zone'] = 'Europe/Istanbul'
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['backup_keep_time'] = 259200 
        gitlab_rails['smtp_enable'] = true 
        gitlab_rails['smtp_user_name'] = "teknik@solvera.com.tr"
        gitlab_rails['gitlab_email_from'] = 'teknik@solvera.com.tr'
        gitlab_rails['gitlab_email_reply_to'] = 'teknik@solvera.com.tr'
        gitlab_rails['gitlab_email_display_name'] = 'GitLab Solvera'
        gitlab_rails['smtp_address'] = "smtp-mail.outlook.com"
        gitlab_rails['smtp_domain'] = "solvera.com.tr"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_password'] = "changeMeToSomethingGood"        
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true 
        gitlab_rails['monitoring_whitelist'] = ['127.0.0.1']
        #unicorn['worker_timeout'] = 60
        #unicorn['worker_processes'] = 3
    networks:
      - gitlab
    ports:
      - "443:443"
      - "80:80"
      - "2222:22"
      - "5010:5010"
    volumes:
      - "$GITLAB_HOME/config:/etc/gitlab"
      - "$GITLAB_HOME/logs:/var/log/gitlab"
      - "$GITLAB_HOME/data:/var/opt/gitlab"
      - "$GITLAB_HOME/certs:/etc/ssl/certs/gitlab" 
networks:
  gitlab:
    external: true
